// ================================================================
// config.js — Constants and Translations (i18n)
// ================================================================

// ===== DATE/TIME CONSTANTS =====
const DAYS_VI = ['Chủ nhật','Thứ hai','Thứ ba','Thứ tư','Thứ năm','Thứ sáu','Thứ bảy'];
const MONTHS_VI = ['tháng 1','tháng 2','tháng 3','tháng 4','tháng 5','tháng 6',
                   'tháng 7','tháng 8','tháng 9','tháng 10','tháng 11','tháng 12'];
const DAYS_EN = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const MONTHS_EN = ['January','February','March','April','May','June',
                   'July','August','September','October','November','December'];

// ===== TRANSLATIONS =====
const LANGS = {
  vi: {
    settings_title:    'Cài đặt nền',
    section_theme:     'Chọn kiểu nền',
    section_image:     'Ảnh nền',
    img_hint:          'Nhập URL ảnh HTTPS để đặt làm nền. Ảnh hiển thị phía sau hiệu ứng gradient.',
    img_opacity_label: 'Độ mờ ảnh',
    img_remove:        'Xoá ảnh nền',
    section_glass:     'Frosted Glass',
    glass_toggle_label:'Hiệu ứng kính mờ',
    glass_blur_label:  'Độ mờ',
    section_css:       'Custom CSS',
    apply_css:         'Áp dụng CSS',
    apply_css_done:    'Đã áp dụng!',
    search_placeholder:'Tìm kiếm trên Google...',
    css_hint_html:     'Viết CSS để tùy chỉnh nền. Dùng selector <code>body</code> hoặc <code>.bg-layer</code>',
    error_img:         'Không tải được ảnh!\nKiểm tra lại:\n• URL có đúng không?\n• Ảnh có phải HTTPS không?\n• Ảnh có cho phép truy cập từ ngoài không?',
    greeting_morning:  '☀️ Chào buổi sáng',
    greeting_noon:     '🌞 Chào buổi trưa',
    greeting_afternoon:'🌤️ Chào buổi chiều',
    greeting_evening:  '🌆 Chào buổi tối',
    greeting_night:    '🌙 Chúc ngủ ngon',
    advanced_settings: 'Cài đặt nâng cao',
    time_bg_toggle:    'Ảnh nền theo thời gian',
    time_bg_hint:      'Thiết lập ảnh khác nhau cho Sáng, Trưa, Chiều, Tối, Đêm.',
    time_morning:      'Sáng (mặt trời mọc)',
    time_noon:         'Trưa (giữa ngày ± 1.5h)',
    time_afternoon:    'Chiều (giữa ngày đến lặn)',
    time_evening:      'Tối (sau khi lặn)',
    time_night:        'Đêm (còn lại)',
    apply_time_bg:     'Áp dụng Ảnh theo thời gian',
    local_upload:      'Tải ảnh lên (Local)',
    unsplash_toggle:   'Ảnh nền theo từ khóa',
    dynamic_sun_toggle:'Đồng bộ mặt trời theo IP',
    todo_title:        'Mục tiêu hôm nay',
    section_sync:      'Dữ liệu & Đồng bộ',
    export_settings:   'Xuất cấu hình',
    import_settings:   'Nhập cấu hình',
  },
  en: {
    settings_title:    'Background Settings',
    section_theme:     'Choose Theme',
    section_image:     'Background Image',
    img_hint:          'Enter an HTTPS image URL to set as background. It appears behind the gradient.',
    img_opacity_label: 'Image opacity',
    img_remove:        'Remove image',
    section_glass:     'Frosted Glass',
    glass_toggle_label:'Glass blur effect',
    glass_blur_label:  'Blur amount',
    section_css:       'Custom CSS',
    apply_css:         'Apply CSS',
    apply_css_done:    'Applied!',
    search_placeholder:'Search on Google...',
    css_hint_html:     'Write CSS to customize the background. Use <code>body</code> or <code>.bg-layer</code>',
    error_img:         'Failed to load image!\nPlease check:\n• Is the URL correct?\n• Is it HTTPS?\n• Does the server allow external access?',
    greeting_morning:  '☀️ Good morning',
    greeting_noon:     '🌞 Good noon',
    greeting_afternoon:'🌤️ Good afternoon',
    greeting_evening:  '🌆 Good evening',
    greeting_night:    '🌙 Good night',
    advanced_settings: 'Advanced Settings',
    time_bg_toggle:    'Time-based background',
    time_bg_hint:      'Set different images for morning, noon, afternoon, evening, and night.',
    time_morning:      'Morning (around sunrise)',
    time_noon:         'Noon (solar noon ± 1.5h)',
    time_afternoon:    'Afternoon (noon to sunset)',
    time_evening:      'Evening (after sunset)',
    time_night:        'Night (remaining)',
    apply_time_bg:     'Apply Time Backgrounds',
    local_upload:      'Upload Local Image',
    unsplash_toggle:   'Dynamic Keyword Image',
    dynamic_sun_toggle:'Sync sun times (IP-based)',
    todo_title:        'Daily Focus',
    section_sync:      'Data & Sync',
    export_settings:   'Export Settings',
    import_settings:   'Import Settings',
  }
};
